version: "3"
services:
    web:
        image: my-registry:55000/auditlogapp:ci-${AUDITAPP_BUILD_NUMBER-10}
        build:
            context: .
        ports:
            - "8000:80"
        depends_on:
            - db
            - migration
        links:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Testing_123"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
    migration:
        build:
            context: .
            dockerfile: Migrations/Dockerfile
        environment:
            SA_USER: "sa"
            SA_PASSWORD: "Testing_123"
        depends_on:
            - db